import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import NextUiProvider from './providers/NextUIProvider'
import QueryProvider from './providers/QueryProvider'
import NavBar from './components/Navbar'



const font = Poppins({ 
  weight: ['400', '600'],
  style: ['normal'],
  subsets: ['latin']
 })

export const metadata: Metadata = {
  title: 'Marvel Universe Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <NextUiProvider>
          <body className={font.className}>
            <NavBar />
            {children}
          </body>
        </NextUiProvider>
      </QueryProvider>
    </html>
  )
}
