import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import NextUiProvider from './providers/NextUIProvider'
import QueryProvider from './providers/QueryProvider'
import NavBar from './components/Navbar'
import Footer from './components/pages/Footer'

const font = Poppins({ 
  weight: ['400', '600', '800', '900'],
  style: ['normal'],
  subsets: ['latin']
 })

export const metadata: Metadata = {
  title: 'Marvel Universe Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProvider>
          <body className={font.className}>
            <NextUiProvider>
                <NavBar />
                {children}
                <Footer />
            </NextUiProvider>
          </body>
      </QueryProvider>
    </html>
  )
}
